app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^checkphone/$', views.checkphone, name='checkphone'),
    url(r'^goodslist/(?P<dealerid>\d+)/$', views.goodslist, name='goodslist'),
    url(r'^goodslist/(?P<dealerid>\d+)/$', views.goodslist,
        name='good'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^addtocart/$', views.addtocart, name='addtocart'),

    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),
url(r'^changecartselectall/$', views.changecartselectall,
    name='changecartselectall'),

    url(r'^addnum/$', views.addnum,name='addnum'),
    url(r'^subnum/$', views.subnum,name='subnum'),
    url(r'^delcart/$', views.delcart, name='delcart'),
    url(r'^delcartall/$', views.delcartall, name='delcartall'),

    url(r'^generateorder/$', views.generateorder, name='generateorder'),
    url(r'orderlist/$', views.orderlist, name='orderlist'),  # 订单列表
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail,
        name='orderdetail'),
    url(r'^orderdetail/$', views.orderdetail,
        name='orderdetail'),

    url(r'^returnurl/$', views.returnurl, name='returnurl'),
    url(r'^appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'),
    url(r'^pay/$', views.pay, name='pay'),

]

python1812alg/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='alg')),
]

app/models.py
from django.db import models

#基础类
class BaseModel(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=20)

    class Meta:
        abstract = True

#轮播图  模型类
class Wheel(BaseModel):
    class Meta:
        db_table = 'alg_wheel'

#品牌上线  模型类
class New_goods (BaseModel):
    class Meta:
        db_table = 'alg_new_goods'

#品牌logo  模型类
class New_goods_brand (BaseModel):
    class Meta:
        db_table = 'alg_new_goods_brand'

class Goods(models.Model):
    # 商品ID
    productid = models.CharField(max_length=20)
    #主页图片
    smallsrc = models.CharField(max_length=200)
    # 商品详情页图片
    bigsrc1 = models.CharField(max_length=200)
    xxsrc1 = models.CharField(max_length=200)

    bigsrc2 = models.CharField(max_length=200)
    xxsrc2 = models.CharField(max_length=200)

    bigsrc3 = models.CharField(max_length=200)
    xxsrc3 = models.CharField(max_length=200)

    bigsrc4 = models.CharField(max_length=200)
    xxsrc4 = models.CharField(max_length=200)

    bigsrc5 = models.CharField(max_length=200)
    xxsrc5 = models.CharField(max_length=200)
    # 商品长名字
    productlongname = models.CharField(max_length=256)
    # 商品信息
    msg = models.CharField(max_length=256)
    #商品打折信息
    salemsg = models.CharField(max_length=256)
    #信息
    news = models.CharField(max_length=256)
    # 商品价格
    oldprice = models.DecimalField(max_digits=6,decimal_places=2)
    # 商品超市价格
    newprice = models.DecimalField(max_digits=6, decimal_places=2)
    # 库存
    remnum = models.IntegerField()
    # 销售
    num = models.IntegerField()
    # 详情页ID
    dealerid = models.CharField(max_length=10)
    class Meta:
        db_table = 'alg_goods'


# 用户 模型类
class User(models.Model):
    phone  = models.CharField(max_length=40, unique=True)
    password = models.CharField(max_length=256)
    name = models.CharField(max_length=100)

    class Meta:
         db_table = 'alg_user'


# 购物车 模型类
class Cart(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(Goods)
    size = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    number = models.IntegerField()
    isselect = models.BooleanField(default=True)
    isdelete = models.BooleanField(default=False)

    class Meta:
        db_table = 'alg_cart'


class Order(models.Model):
    user = models.ForeignKey(User)
    createtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    status = models.IntegerField(default=0)
    identifier = models.CharField(max_length=256)

class OrderGoods(models.Model):
    order = models.ForeignKey(Order)
    goods = models.ForeignKey(Goods)
    number = models.IntegerField()

templates/genrateorder.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>生成订单</title>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
    <link rel="stylesheet" type="text/css" href=
            "{% static 'css/base.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/top_footer.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/cart.css' %}"/>
    <script src="{% static 'js/jquery-1.12.0.js' %}"></script>
    <!--再导入cookie-->
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/genrateorder.js' %}"></script>
</head>

<body>

<div id="header">
    <!------------top部分------------>
    <div class="top">
        <div class="top_head">
            <div class="top_l">华盛奥特莱斯全渠道一体化零售平台</div>
            <div class="top_r">
                <ul>
                    <li class="top_login">
                        <a href="{% url 'alg:login' %}">
                            用户：{{ user.name | default:'未登录' }}
                        </a>
                        {% if user %}
                            <a href="{% url 'alg:logout' %}">退出登录</a>
                        {% endif %}
                    </li>
                    <li class="top_register">
                        <a href="{% url 'alg:register' %}"
                           target="_blank">免费注册</a>
                    </li>
                    <li class="top_mygo">
                        <a href="{% url 'alg:index' %}">我的奥莱购</a>
                        <dl class="mygo_down">
                            <dd>
                                <a href="{% url 'alg:orderlist' %}">我的订单</a>
                            </dd>
                            <dd>
                                <a href="#">我的收藏</a>
                            </dd>
                            <dd>
                                <a href="#">我的优惠卷</a>
                            </dd>
                            <dd>
                                <a href="{% url 'alg:cart' %}">我的购物车</a>
                            </dd>
                        </dl>

                    </li>
                    <li>
                        <a target="_blank" href="#">手机APP</a>
                    </li>
                    <li class="help_center">
                        <a href="#">帮助中心</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-------logo------->
    <div class="head_blank">
        <div class="head_msg">
            <div class="logo_l">
                <a href="{% url 'alg:index' %}" target="_blank">
                    <img src="{% static 'img/logo_01.jpg' %}">
                </a>

            </div>
        </div>
        <div class="head_search">
            <div class="search_box">
                <div class="search_text">
                    <input type="text" id="keyword"
                           class="search_l_text" value="拉夏贝尔"
                           maxlength="100">
                </div>
                <div class="search_btn">
                    <input type="button" class="search_r_btn"
                           value="搜索">
                </div>
            </div>

        </div>
    </div>
</div>

<div class="cart_ad">
    <a href="#">
        <img src="{% static 'img/cart_ad.jpg' %}">
    </a>
</div>

<!--------购物车清单---------->
<!--有商品  商品清单显示-->

<div class="cart_msg">
    <div class="cartlist_tittle_l">订单
    </div>
    {#    <div class="cartlist_tittle_r" style="display: none;">#}
    {#        <img src="{% static 'img/alg-lodding.gif' %}">#}
    {#    </div>#}
</div>

<!--------购物车详情---------->
<div class="cart_msg">
    <div class="cart_msg_a">
        {% for ordergood in order.ordergoods_set.all %}
            <li>
            <img src="{{ ordergood.goods.smallsrc }}" alt=""
                 style="width: 100px;height: 100px">
            <span style="font-size: 20px;margin-left: 20px"
            >{{ ordergood.goods.productlongname }}</span>
            &nbsp;
            <i style="font-size: 20px; margin-left: 20px">x
                {{ ordergood.number }}</i>
            </li>
        {% endfor %}
    <button class="btn btn-default" id="alipay"
                    data-orderid="{{ order.id }}"
                    style="font-size: 20px; margin-left: 20px">支付
            </button>
    </div>
</div>


<!----------footer部分----------->
<div id="footer">
    <div class="foot_top">
        <div class="foot_sign">
            <ul>
                <li><i class="foot_icon1"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>100%</dt>
                            <dd>全场正品保证</dd>
                        </dl>
                    </div>
                </li>
                <li class="foot_sign_li"><i class="foot_icon2"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>Mall</dt>
                            <dd>实付满58包邮</dd>
                        </dl>
                    </div>
                </li>
                <li class="foot_sign_li"><i class="foot_icon3"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>SALE</dt>
                            <dd>每天低价特卖</dd>
                        </dl>
                    </div>
                </li>
                <li class="foot_sign_li"><i class="foot_icon4"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>7Days</dt>
                            <dd>七天无理由换货</dd>
                        </dl>
                    </div>
                </li>
                <li class="foot_sign_li"><i class="foot_icon5"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>全渠道</dt>
                            <dd>线上线下同步服务</dd>
                        </dl>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="foot_conter">
        <div class="foot_guild1">
            <p>购物指南</p>
            <ul>
                <li><a href="#" target="_blank">购物流程</a></li>
                <li><a href="#" target="_blank">用户注册</a></li>
                <li><a href="#" target="_blank">提交订单</a></li>
                <li><a href="#" target="_blank">找回密码</a></li>
                <li><a href="#" target="_blank">常见问题</a></li>
                <li><a href="#" target="_blank">跨境汇需知</a></li>
            </ul>
        </div>
        <div class="foot_guild2">
            <p>支付方式</p>
            <ul>
                <li><a href="#" target="_blank">网银支付</a></li>
                <li><a href="#" target="_blank">第三方支付</a></li>
                <li><a href="#" target="_blank">支付常见问题</a></li>
            </ul>
        </div>
        <div class="foot_guild2">
            <p>配送方式</p>
            <ul>
                <li><a href="#" target="_blank">配送服务查询</a></li>
                <li><a href="#" target="_blank">配送服务说明</a></li>
                <li><a href="#" target="_blank">验货与签收</a></li>
                <li><a href="#" target="_blank">包邮政策</a></li>
            </ul>
        </div>
        <div class="foot_guild2">
            <p>售后服务</p>
            <ul>
                <li><a href="#" target="_blank">退换货政策</a></li>
                <li><a href="#" target="_blank">退换货管理</a></li>
                <li><a href="#" target="_blank">退换货说明</a></li>
                <li><a href="#" target="_blank">退换货流程</a></li>
                <li><a href="#" target="_blank">跨境汇售后服务</a></li>
            </ul>
        </div>
        <div class="foot_guild2">
            <p>线下奥莱购购物中心</p>
            <ul>
                <li><a href="#" target="_blank">深圳华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">南宁华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">南昌华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">西安华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">郑州华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">哈尔滨华盛奥特莱斯</a></li>
            </ul>
        </div>
        <div class="foot_guild3">
            <div class="foot_official">
                <div class="foot_of_l">
                    <a href="#" target="_blank"><i
                            class="foot_of_icon1"></i></a>
                    <p>官方微博</p>
                </div>
                <div class="foot_of_r">
                    <a href="#" target="_blank"><i
                            class="foot_of_icon2"></i></a>
                    <p>官方应用</p>
                </div>
            </div>
            <div class="foot_phone font_phone_icon">
                <p>400 - 184 - 8866</p>
                <span>周一至周日：09:00-21:00</span>
            </div>
            <div class="onlne_service">
                <a href="#" target="_blank"><img
                        src="{% static 'img/chat.png' %}"></a>
            </div>
        </div>
    </div>
    <div class="foot_bottom">
        <div class="foot_link">
            <div class="foot_rel">
                <ul>
                    <li>关于奥莱购</li>
                    <li>联系我们</li>
                    <li>诚聘英才</li>
                    <li>商务合作</li>
                    <li>友情链接</li>
                    <li>华南城网</li>
                    <li>华盛Outlets</li>
                </ul>
            </div>
            <div class="foot_copyright">
                Copyright © 2013-2016 深圳华盛电子商务有限公司 粤ICP备16081451-1号 All
                Right<br><br>
                深圳市龙岗区平湖华南城1号交易广场4楼奥莱购（深圳华盛电子商务有限公司）
            </div>
            <div class="foot_partner">
                <ul>
                    <li class="partner_icon1"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon2"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon3"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon4"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon5"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon6"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon7"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon8"><a href="#"
                                                 target="_blank"></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>


</body>

</html>

templates/orderdetail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>生成订单</title>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
    <link rel="stylesheet" type="text/css" href=
            "{% static 'css/base.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/top_footer.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/cart.css' %}"/>
    <script src="{% static 'js/jquery-1.12.0.js' %}"></script>
    <!--再导入cookie-->
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/orderdetail.js' %}"></script>
</head>

<body>

<div id="header">
    <!------------top部分------------>
    <div class="top">
        <div class="top_head">
            <div class="top_l">华盛奥特莱斯全渠道一体化零售平台</div>
            <div class="top_r">
                <ul>
                    <li class="top_login">
                        <a href="{% url 'alg:login' %}">
                            用户：{{ user.name | default:'未登录' }}
                        </a>
                        {% if user %}
                            <a href="{% url 'alg:logout' %}">退出登录</a>
                        {% endif %}
                    </li>
                    <li class="top_register">
                        <a href="{% url 'alg:register' %}"
                           target="_blank">免费注册</a>
                    </li>
                    <li class="top_mygo">
                        <a href="{% url 'alg:index' %}">我的奥莱购</a>
                        <dl class="mygo_down">
                            <dd>
                                <a href="{% url 'alg:orderlist' %}">我的订单</a>
                            </dd>
                            <dd>
                                <a href="#">我的收藏</a>
                            </dd>
                            <dd>
                                <a href="#">我的优惠卷</a>
                            </dd>
                            <dd>
                                <a href="{% url 'alg:cart' %}">我的购物车</a>
                            </dd>
                        </dl>

                    </li>
                    <li>
                        <a target="_blank" href="#">手机APP</a>
                    </li>
                    <li class="help_center">
                        <a href="#">帮助中心</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-------logo------->
    <div class="head_blank">
        <div class="head_msg">
            <div class="logo_l">
                <a href="{% url 'alg:index' %}" target="_blank">
                    <img src="{% static 'img/logo_01.jpg' %}">
                </a>

            </div>
        </div>
        <div class="head_search">
            <div class="search_box">
                <div class="search_text">
                    <input type="text" id="keyword"
                           class="search_l_text" value="拉夏贝尔"
                           maxlength="100">
                </div>
                <div class="search_btn">
                    <input type="button" class="search_r_btn"
                           value="搜索">
                </div>
            </div>

        </div>
    </div>
</div>

<div class="cart_ad">
    <a href="#">
        <img src="{% static 'img/cart_ad.jpg' %}">
    </a>
</div>

<!--------购物车清单---------->
<!--有商品  商品清单显示-->

<div class="cart_msg">
    <div class="cartlist_tittle_l">订单详情
    </div>
</div>

<!--------购物车详情---------->
<div class="cart_msg">

    <div class="orderdetail">
        <p style="font-size: 20px; margin-left: 20px">
            订单号: {{ order.identifier }}
        </p>
        <p style="font-size: 20px; margin-left: 20px">订单创建时间：
            {{ order.createtime }}</p>
        {% for ordergood in order.ordergoods_set.all %}
            <li>
            <img src="{{ ordergood.goods.smallsrc }}" alt=""
                 style="width: 100px;height: 100px">
            <span style="font-size: 20px;margin-left: 20px"
            >{{ ordergood.goods.productlongname }}</span>
            &nbsp;
            <i style="font-size: 20px; margin-left: 20px">x
                {{ ordergood.number }}</i>
            </li>

        {% endfor %}
        {% if order.status == 0 %}
            <button class="btn btn-default" id="alipay"
                    data-orderid="{{ order.id }}"
                    style="font-size: 20px; margin-left: 20px">支付
            </button>
        {% elif order.status == 1 %}
            <button class="btn btn-default"
                    style="font-size: 20px; margin-left: 20px"> 已支付，待发货
            </button>
        {% endif %}

    </div>
</div>

<!----------footer部分----------->
<div id="footer">
    <div class="foot_top">
        <div class="foot_sign">
            <ul>
                <li><i class="foot_icon1"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>100%</dt>
                            <dd>全场正品保证</dd>
                        </dl>
                    </div>
                </li>
                <li class="foot_sign_li"><i class="foot_icon2"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>Mall</dt>
                            <dd>实付满58包邮</dd>
                        </dl>
                    </div>
                </li>
                <li class="foot_sign_li"><i class="foot_icon3"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>SALE</dt>
                            <dd>每天低价特卖</dd>
                        </dl>
                    </div>
                </li>
                <li class="foot_sign_li"><i class="foot_icon4"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>7Days</dt>
                            <dd>七天无理由换货</dd>
                        </dl>
                    </div>
                </li>
                <li class="foot_sign_li"><i class="foot_icon5"></i>
                    <div class="foot_tip">
                        <dl>
                            <dt>全渠道</dt>
                            <dd>线上线下同步服务</dd>
                        </dl>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="foot_conter">
        <div class="foot_guild1">
            <p>购物指南</p>
            <ul>
                <li><a href="#" target="_blank">购物流程</a></li>
                <li><a href="#" target="_blank">用户注册</a></li>
                <li><a href="#" target="_blank">提交订单</a></li>
                <li><a href="#" target="_blank">找回密码</a></li>
                <li><a href="#" target="_blank">常见问题</a></li>
                <li><a href="#" target="_blank">跨境汇需知</a></li>
            </ul>
        </div>
        <div class="foot_guild2">
            <p>支付方式</p>
            <ul>
                <li><a href="#" target="_blank">网银支付</a></li>
                <li><a href="#" target="_blank">第三方支付</a></li>
                <li><a href="#" target="_blank">支付常见问题</a></li>
            </ul>
        </div>
        <div class="foot_guild2">
            <p>配送方式</p>
            <ul>
                <li><a href="#" target="_blank">配送服务查询</a></li>
                <li><a href="#" target="_blank">配送服务说明</a></li>
                <li><a href="#" target="_blank">验货与签收</a></li>
                <li><a href="#" target="_blank">包邮政策</a></li>
            </ul>
        </div>
        <div class="foot_guild2">
            <p>售后服务</p>
            <ul>
                <li><a href="#" target="_blank">退换货政策</a></li>
                <li><a href="#" target="_blank">退换货管理</a></li>
                <li><a href="#" target="_blank">退换货说明</a></li>
                <li><a href="#" target="_blank">退换货流程</a></li>
                <li><a href="#" target="_blank">跨境汇售后服务</a></li>
            </ul>
        </div>
        <div class="foot_guild2">
            <p>线下奥莱购购物中心</p>
            <ul>
                <li><a href="#" target="_blank">深圳华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">南宁华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">南昌华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">西安华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">郑州华盛奥特莱斯</a></li>
                <li><a href="#" target="_blank">哈尔滨华盛奥特莱斯</a></li>
            </ul>
        </div>
        <div class="foot_guild3">
            <div class="foot_official">
                <div class="foot_of_l">
                    <a href="#" target="_blank"><i
                            class="foot_of_icon1"></i></a>
                    <p>官方微博</p>
                </div>
                <div class="foot_of_r">
                    <a href="#" target="_blank"><i
                            class="foot_of_icon2"></i></a>
                    <p>官方应用</p>
                </div>
            </div>
            <div class="foot_phone font_phone_icon">
                <p>400 - 184 - 8866</p>
                <span>周一至周日：09:00-21:00</span>
            </div>
            <div class="onlne_service">
                <a href="#" target="_blank"><img
                        src="{% static 'img/chat.png' %}"></a>
            </div>
        </div>
    </div>
    <div class="foot_bottom">
        <div class="foot_link">
            <div class="foot_rel">
                <ul>
                    <li>关于奥莱购</li>
                    <li>联系我们</li>
                    <li>诚聘英才</li>
                    <li>商务合作</li>
                    <li>友情链接</li>
                    <li>华南城网</li>
                    <li>华盛Outlets</li>
                </ul>
            </div>
            <div class="foot_copyright">
                Copyright © 2013-2016 深圳华盛电子商务有限公司 粤ICP备16081451-1号 All
                Right<br><br>
                深圳市龙岗区平湖华南城1号交易广场4楼奥莱购（深圳华盛电子商务有限公司）
            </div>
            <div class="foot_partner">
                <ul>
                    <li class="partner_icon1"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon2"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon3"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon4"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon5"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon6"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon7"><a href="#"
                                                 target="_blank"></a>
                    </li>
                    <li class="partner_icon8"><a href="#"
                                                 target="_blank"></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>

</body>
</html>